## I'm Learning numpy

> **What is numpy?**
> <p style="text-align:justify">NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.</p>

#### Importing numpy

In [3]:
import numpy as np

#### Creating array

In [4]:
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

#### Diff. b/w python list and numpy array

In [5]:
import time

##### Python List Speed Test

In [6]:
python_list = [i for i in range(1000000)]
start_time = time.process_time()
add_two = [i+2 for i in python_list]
end_time = time.process_time()
end_time - start_time

0.109375

##### Numpy Array Speed Test

In [7]:
numpy_array = np.arange(1000000)
start_time = time.process_time()
add_two = numpy_array+2
end_time = time.process_time()
end_time - start_time

0.015625

In [8]:
# Deleting varaiables
del start_time, end_time, python_list, numpy_array, add_two

#### Arrays in numpy

1D Array

In [9]:
np.array([1, 2, 3, 4, 5], dtype=np.int8)

array([1, 2, 3, 4, 5], dtype=int8)

2D Array

In [10]:
np.array([[1, 2, 3, 4, 5],
          [6, 7, 8, 9, 10]], dtype=np.int8)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int8)

3D Array

In [11]:
np.array([[[1, 2, 3, 4, 5],
          [6, 7, 8, 9, 10]],
          
          [[1, 2, 3, 4, 5],
          [6, 7, 8, 9, 10]]], dtype=np.int8)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]], dtype=int8)

##### Arrays of Zeros

In [12]:
# 1D
print("1D:", np.zeros(2), "\n")
# 2D
print("2D:", np.zeros((2, 2)), "\n")
# 3D
print("3D:", np.zeros((2, 2, 2)), "\n")

1D: [0. 0.] 

2D: [[0. 0.]
 [0. 0.]] 

3D: [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]] 



##### Arrays of Ones

In [13]:
# 1D
print("1D:", np.ones(2), "\n")
# 2D
print("2D:", np.ones((2, 2)), "\n")
# 3D
print("3D:", np.ones((2, 2, 2)), "\n")

1D: [1. 1.] 

2D: [[1. 1.]
 [1. 1.]] 

3D: [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]] 



##### Empty Array
The function `np.empty()` creates an array whose initial content is random and depends on the state of the memory.

In [14]:
# 2x2 empty array
np.empty((2, 2))

array([[1., 1.],
       [1., 1.]])

Creating an Array with a range of elements using `np.arange()` function similar to `range()` function

In [15]:
np.arange(100, 1, -2)

array([100,  98,  96,  94,  92,  90,  88,  86,  84,  82,  80,  78,  76,
        74,  72,  70,  68,  66,  64,  62,  60,  58,  56,  54,  52,  50,
        48,  46,  44,  42,  40,  38,  36,  34,  32,  30,  28,  26,  24,
        22,  20,  18,  16,  14,  12,  10,   8,   6,   4,   2])

You can also use `np.linspace()` to create an array with values that are spaced linearly in a specified interval

In [16]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

##### Random Arrays

In [17]:
np.random.rand(5, 5)

array([[2.10067749e-01, 3.18273052e-01, 4.12186632e-01, 1.83512291e-01,
        2.39358447e-01],
       [8.41931305e-01, 8.76891121e-01, 4.17592398e-01, 7.38759445e-04,
        6.10707728e-01],
       [6.13752349e-01, 8.88155632e-01, 8.59532854e-01, 5.69800425e-01,
        3.79850761e-02],
       [1.59091191e-01, 9.50745220e-01, 3.33116537e-01, 6.68232559e-01,
        2.88871371e-01],
       [8.41512032e-01, 2.78285023e-01, 9.51402785e-01, 6.66682199e-01,
        8.29117561e-01]])

In [18]:
np.random.randint(1, 10, (4, 4), dtype=np.int16)

array([[1, 3, 1, 6],
       [1, 6, 8, 5],
       [3, 7, 5, 6],
       [4, 3, 4, 9]], dtype=int16)

In [19]:
# Returns random float array of given size
np.random.random((3, 3))

array([[0.94844118, 0.70191709, 0.14814828],
       [0.90743595, 0.26496976, 0.25243001],
       [0.97919635, 0.91365972, 0.66561028]])

To sample from N evenly spaced floating-point numbers between a and b, use:

```py
 a + (b - a) * (np.random.random_integers(N) - 1) / (N - 1.)
 ```

In [20]:
np.random.random_integers(1, 5, size=(2, 2))

C:\Users\hp\AppData\Local\Temp\ipykernel_8332\1565548986.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  np.random.random_integers(1, 5, size=(2, 2))


array([[2, 5],
       [1, 4]])

##### Randomly Shuffling an Array

In [21]:
arr = np.arange(1, 10)
np.random.shuffle(arr)
arr

array([2, 9, 8, 6, 3, 7, 4, 5, 1])

##### Sorting
Sorting an element is simple with `np.sort()`. You can specify the axis, kind, and order when you call the function.

In [22]:
arr = np.array([[48, 60, 46,  1],
       [40, 63, 39, 55],
       [47, 37, 51, 53],
       [28, 25, 61, 99]])
arr

array([[48, 60, 46,  1],
       [40, 63, 39, 55],
       [47, 37, 51, 53],
       [28, 25, 61, 99]])

In [23]:
# Sorting along 1 axis
# Sorting ELements of each row
arr1 = arr.copy()
arr1.sort()
arr1

array([[ 1, 46, 48, 60],
       [39, 40, 55, 63],
       [37, 47, 51, 53],
       [25, 28, 61, 99]])

In [24]:
# Sorting along 0 axis
# Sorting Rows
arr2 = arr.copy()
arr2.sort(axis=0)
arr2

array([[28, 25, 39,  1],
       [40, 37, 46, 53],
       [47, 60, 51, 55],
       [48, 63, 61, 99]])

##### Concatenation

In [25]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

##### Checking shape, size, dimensions and datatype of numpy array

In [26]:
arr = np.random.randint(1, 10, (4, 4), dtype=np.int16)

arr.shape, arr.size, arr.ndim, arr.dtype

((4, 4), 16, 2, dtype('int16'))

##### Reshaping

In [27]:
arr.reshape((2, 8))

array([[4, 8, 1, 9, 6, 3, 3, 1],
       [8, 2, 9, 4, 8, 6, 9, 3]], dtype=int16)

#### How to convert a 1D array into a 2D array (how to add a new axis to an array)
You can use `np.newaxis` and `np.expand_dims` to increase the dimensions of your existing array.

In [28]:
arr = np.random.randint(1, 10, 16, dtype=np.int16)
arr.shape

(16,)

In [29]:
arr2 = arr[np.newaxis,:]
arr2.shape

(1, 16)

In [30]:
arr2 = arr[:, np.newaxis]
arr2.shape

(16, 1)

In [31]:
arr2 = np.expand_dims(arr, axis=0)
arr2

array([[4, 1, 7, 8, 1, 9, 7, 8, 3, 5, 5, 4, 8, 8, 5, 7]], dtype=int16)

In [32]:
arr2 = np.expand_dims(arr, axis=1)
arr2

array([[4],
       [1],
       [7],
       [8],
       [1],
       [9],
       [7],
       [8],
       [3],
       [5],
       [5],
       [4],
       [8],
       [8],
       [5],
       [7]], dtype=int16)

#### Indexing and Slicing

![Image](https://numpy.org/doc/stable/_images/np_indexing.png)

In [33]:
data = np.array([1, 2, 3])
data[-2:]

array([2, 3])

##### Resverse an Array

In [55]:
data[::-1]

array([3, 2, 1])

In [36]:
arr = np.random.randint(1, 20, (4, 4))
arr

array([[ 5, 15,  3, 14],
       [18,  7,  4,  3],
       [15, 19, 12, 14],
       [ 9, 10, 11, 11]])

##### Indexing of 2D Array

In [62]:
arr[2:,2:]

array([[12, 14],
       [11, 11]])

##### Reserving rows and row elements of 2D array

In [63]:
arr[::-1,::-1]

array([[11, 11, 10,  9],
       [14, 12, 19, 15],
       [ 3,  4,  7, 18],
       [14,  3, 15,  5]])

You can easily print all of the values in the array that are less than 5.

In [38]:
arr[arr < 5]

array([3, 4, 3])

You can select elements that are divisible by 2

In [39]:
arr[arr%2 == 0]

array([14, 18,  4, 12, 14, 10])

Or you can select elements that satisfy two conditions using the `&` and `|` operators

In [40]:
arr[(arr >= 5) & (arr <= 10)]

array([ 5,  7,  9, 10])

In [43]:
arr[(arr == 5) | (arr == 10)]

array([ 5, 10])

### How to create an array from existing data

In [66]:
arr = np.random.randint(1, 30, (5, 5))
arr

array([[21, 25, 21, 19,  6],
       [12,  7, 27,  8,  8],
       [ 7,  4,  4,  1,  6],
       [10,  5, 26, 20,  7],
       [10, 22, 13, 17, 14]])

You can create a new array from a section of your array by slice your array.

In [69]:
# arr2 is new array
arr2 = arr[2:4]
arr2

array([[ 7,  4,  4,  1,  6],
       [10,  5, 26, 20,  7]])

You can also stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, `a` and `b`:


In [77]:
a = np.array([[1, 1],
               [2, 2]])
b = np.array([[3, 3],
               [4, 4]])

In [71]:
# Vertical
np.vstack((a, b))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [79]:
# Horizontal
np.hstack((a, b))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

You can split an array into several smaller arrays using `np.hsplit()` and `np.vsplit()`

In [87]:
arr = arr[:4, :4]
arr

array([[21, 25, 21, 19],
       [12,  7, 27,  8],
       [ 7,  4,  4,  1],
       [10,  5, 26, 20]])

In [96]:
# Divide into 4 equal arrays horizontally(rowwise)
np.hsplit(arr, 4)

[array([[21],
        [12],
        [ 7],
        [10]]),
 array([[25],
        [ 7],
        [ 4],
        [ 5]]),
 array([[21],
        [27],
        [ 4],
        [26]]),
 array([[19],
        [ 8],
        [ 1],
        [20]])]

In [97]:
# Divide into 4 equal arrays vertically(columnwise)
np.vsplit(arr, 4)

[array([[21, 25, 21, 19]]),
 array([[12,  7, 27,  8]]),
 array([[7, 4, 4, 1]]),
 array([[10,  5, 26, 20]])]

In [109]:
# Split after 2 and 4 column
np.hsplit(arr, (2, 4))

[array([[21, 25],
        [12,  7],
        [ 7,  4],
        [10,  5]]),
 array([[21, 19],
        [27,  8],
        [ 4,  1],
        [26, 20]]),
 array([], shape=(4, 0), dtype=int32)]

In [110]:
# Split after 1, 2 and 4 row
np.vsplit(arr, (1, 2, 4))

[array([[21, 25, 21, 19]]),
 array([[12,  7, 27,  8]]),
 array([[ 7,  4,  4,  1],
        [10,  5, 26, 20]]),
 array([], shape=(0, 4), dtype=int32)]

You can use the `view` method to create a new array object that looks at the same data as the original array (a shallow copy).

<p style="text-align:justify">Views are an important NumPy concept! NumPy functions, as well as operations like indexing and slicing, will return views whenever possible. This saves memory and is faster (no copy of the data has to be made). However it’s important to be aware of this - modifying data in a view also modifies the original array!</p>

In [111]:
arr

array([[21, 25, 21, 19],
       [12,  7, 27,  8],
       [ 7,  4,  4,  1],
       [10,  5, 26, 20]])

In [115]:
arr2 = arr[2:, 2:]
arr2[0, 0] = 2
arr

array([[21, 25, 21, 19],
       [12,  7, 27,  8],
       [ 7,  4,  2,  1],
       [10,  5, 26, 20]])

Using the `copy` method will make a complete copy of the array and its data (a deep copy).

In [117]:
arr2 = arr.copy()
arr2[0, 0] = 0
arr

array([[21, 25, 21, 19],
       [12,  7, 27,  8],
       [ 7,  4,  2,  1],
       [10,  5, 26, 20]])

### Basic array operations