## I'm Learning numpy

> **What is numpy?**
> <p style="text-align:justify">NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.</p>

#### Importing numpy

In [1]:
import numpy as np

#### Creating array

In [2]:
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

#### Diff. b/w python list and numpy array

In [3]:
import time

##### Python List Speed Test

In [4]:
python_list = [i for i in range(1000000)]
start_time = time.process_time()
add_two = [i+2 for i in python_list]
end_time = time.process_time()
end_time - start_time

0.15625

##### Numpy Array Speed Test

In [5]:
numpy_array = np.arange(1000000)
start_time = time.process_time()
add_two = numpy_array+2
end_time = time.process_time()
end_time - start_time

0.015625

In [6]:
# Deleting varaiables
del start_time, end_time, python_list, numpy_array, add_two

#### Arrays in numpy

1D Array

In [7]:
np.array([1, 2, 3, 4, 5], dtype=np.int8)

array([1, 2, 3, 4, 5], dtype=int8)

2D Array

In [8]:
np.array([[1, 2, 3, 4, 5],
          [6, 7, 8, 9, 10]], dtype=np.int8)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int8)

3D Array

In [9]:
np.array([[[1, 2, 3, 4, 5],
          [6, 7, 8, 9, 10]],
          
          [[1, 2, 3, 4, 5],
          [6, 7, 8, 9, 10]]], dtype=np.int8)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]], dtype=int8)

##### Arrays of Zeros

In [10]:
# 1D
print("1D:", np.zeros(2), "\n")
# 2D
print("2D:", np.zeros((2, 2)), "\n")
# 3D
print("3D:", np.zeros((2, 2, 2)), "\n")

1D: [0. 0.] 

2D: [[0. 0.]
 [0. 0.]] 

3D: [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]] 



##### Arrays of Ones

In [11]:
# 1D
print("1D:", np.ones(2), "\n")
# 2D
print("2D:", np.ones((2, 2)), "\n")
# 3D
print("3D:", np.ones((2, 2, 2)), "\n")

1D: [1. 1.] 

2D: [[1. 1.]
 [1. 1.]] 

3D: [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]] 



##### Empty Array
The function `np.empty()` creates an array whose initial content is random and depends on the state of the memory.

In [12]:
# 2x2 empty array
np.empty((2, 2))

array([[1., 1.],
       [1., 1.]])

Creating an Array with a range of elements using `np.arange()` function similar to `range()` function

In [13]:
np.arange(100, 1, -2)

array([100,  98,  96,  94,  92,  90,  88,  86,  84,  82,  80,  78,  76,
        74,  72,  70,  68,  66,  64,  62,  60,  58,  56,  54,  52,  50,
        48,  46,  44,  42,  40,  38,  36,  34,  32,  30,  28,  26,  24,
        22,  20,  18,  16,  14,  12,  10,   8,   6,   4,   2])

You can also use `np.linspace()` to create an array with values that are spaced linearly in a specified interval

In [14]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

##### Random Arrays

In [15]:
np.random.rand(5, 5)

array([[0.82345906, 0.25017447, 0.94844007, 0.32761722, 0.55556297],
       [0.69626738, 0.37972568, 0.44450526, 0.41903338, 0.70038895],
       [0.47777593, 0.05828031, 0.77356214, 0.86264609, 0.30087825],
       [0.81238106, 0.09399991, 0.47838802, 0.63097153, 0.23646582],
       [0.62805368, 0.48169056, 0.43022636, 0.21319091, 0.94428027]])

In [16]:
np.random.randint(1, 10, (4, 4), dtype=np.int16)

array([[7, 3, 9, 5],
       [8, 3, 3, 9],
       [4, 1, 3, 2],
       [4, 2, 1, 4]], dtype=int16)

In [17]:
# Returns random float array of given size
np.random.random((3, 3))

array([[0.48216345, 0.51240707, 0.15411218],
       [0.08162532, 0.02698725, 0.15785116],
       [0.87560604, 0.27945302, 0.96830667]])

To sample from N evenly spaced floating-point numbers between a and b, use:

```py
 a + (b - a) * (np.random.random_integers(N) - 1) / (N - 1.)
 ```

In [18]:
np.random.random_integers(1, 5, size=(2, 2))

C:\Users\hp\AppData\Local\Temp\ipykernel_2344\1565548986.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  np.random.random_integers(1, 5, size=(2, 2))


array([[5, 2],
       [3, 4]])

##### Randomly Shuffling an Array

In [19]:
arr = np.arange(1, 10)
np.random.shuffle(arr)
arr

array([3, 6, 8, 5, 2, 1, 7, 9, 4])

##### Sorting
Sorting an element is simple with `np.sort()`. You can specify the axis, kind, and order when you call the function.

In [20]:
arr = np.array([[48, 60, 46,  1],
       [40, 63, 39, 55],
       [47, 37, 51, 53],
       [28, 25, 61, 99]])
arr

array([[48, 60, 46,  1],
       [40, 63, 39, 55],
       [47, 37, 51, 53],
       [28, 25, 61, 99]])

In [21]:
# Sorting along 1 axis
# Sorting ELements of each row
arr1 = arr.copy()
arr1.sort()
arr1

array([[ 1, 46, 48, 60],
       [39, 40, 55, 63],
       [37, 47, 51, 53],
       [25, 28, 61, 99]])

In [22]:
# Sorting along 0 axis
# Sorting Rows
arr2 = arr.copy()
arr2.sort(axis=0)
arr2

array([[28, 25, 39,  1],
       [40, 37, 46, 53],
       [47, 60, 51, 55],
       [48, 63, 61, 99]])

##### Concatenation

In [23]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

##### Checking shape, size, dimensions and datatype of numpy array

In [24]:
arr = np.random.randint(1, 10, (4, 4), dtype=np.int16)

arr.shape, arr.size, arr.ndim, arr.dtype

((4, 4), 16, 2, dtype('int16'))

##### Reshaping

In [25]:
arr.reshape((2, 8))

array([[2, 3, 8, 6, 9, 4, 9, 1],
       [9, 4, 3, 7, 2, 8, 5, 2]], dtype=int16)

#### How to convert a 1D array into a 2D array (how to add a new axis to an array)
You can use `np.newaxis` and `np.expand_dims` to increase the dimensions of your existing array.

In [26]:
arr = np.random.randint(1, 10, 16, dtype=np.int16)
arr.shape

(16,)

In [27]:
arr2 = arr[np.newaxis,:]
arr2.shape

(1, 16)

In [28]:
arr2 = arr[:, np.newaxis]
arr2.shape

(16, 1)

In [29]:
arr2 = np.expand_dims(arr, axis=0)
arr2

array([[8, 8, 6, 2, 7, 8, 3, 7, 5, 8, 2, 2, 6, 1, 4, 9]], dtype=int16)

In [30]:
arr2 = np.expand_dims(arr, axis=1)
arr2

array([[8],
       [8],
       [6],
       [2],
       [7],
       [8],
       [3],
       [7],
       [5],
       [8],
       [2],
       [2],
       [6],
       [1],
       [4],
       [9]], dtype=int16)

#### Indexing and Slicing

![Image](https://numpy.org/doc/stable/_images/np_indexing.png)

In [31]:
data = np.array([1, 2, 3])
data[-2:]

array([2, 3])

##### Resverse an Array

In [32]:
data[::-1]

array([3, 2, 1])

In [33]:
arr = np.random.randint(1, 20, (4, 4))
arr

array([[ 4,  5,  6,  4],
       [19, 17, 12,  6],
       [14,  3, 19, 17],
       [ 2,  1, 12, 16]])

##### Indexing of 2D Array

In [34]:
arr[2:,2:]

array([[19, 17],
       [12, 16]])

##### Reserving rows and row elements of 2D array

In [35]:
arr[::-1,::-1]

array([[16, 12,  1,  2],
       [17, 19,  3, 14],
       [ 6, 12, 17, 19],
       [ 4,  6,  5,  4]])

You can easily print all of the values in the array that are less than 5.

In [36]:
arr[arr < 5]

array([4, 4, 3, 2, 1])

You can select elements that are divisible by 2

In [37]:
arr[arr%2 == 0]

array([ 4,  6,  4, 12,  6, 14,  2, 12, 16])

Or you can select elements that satisfy two conditions using the `&` and `|` operators

In [38]:
arr[(arr >= 5) & (arr <= 10)]

array([5, 6, 6])

In [39]:
arr[(arr == 5) | (arr == 10)]

array([5])

### How to create an array from existing data

In [40]:
arr = np.random.randint(1, 30, (5, 5))
arr

array([[15, 17, 24, 28, 29],
       [15, 20, 10, 18, 27],
       [ 6, 18,  8,  5, 12],
       [25, 17,  4, 22, 14],
       [28, 23, 13,  6,  8]])

You can create a new array from a section of your array by slice your array.

In [41]:
# arr2 is new array
arr2 = arr[2:4]
arr2

array([[ 6, 18,  8,  5, 12],
       [25, 17,  4, 22, 14]])

You can also stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, `a` and `b`:


In [42]:
a = np.array([[1, 1],
               [2, 2]])
b = np.array([[3, 3],
               [4, 4]])

In [43]:
# Vertical
np.vstack((a, b))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [44]:
# Horizontal
np.hstack((a, b))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

You can split an array into several smaller arrays using `np.hsplit()` and `np.vsplit()`

In [45]:
arr = arr[:4, :4]
arr

array([[15, 17, 24, 28],
       [15, 20, 10, 18],
       [ 6, 18,  8,  5],
       [25, 17,  4, 22]])

In [46]:
# Divide into 4 equal arrays horizontally(rowwise)
np.hsplit(arr, 4)

[array([[15],
        [15],
        [ 6],
        [25]]),
 array([[17],
        [20],
        [18],
        [17]]),
 array([[24],
        [10],
        [ 8],
        [ 4]]),
 array([[28],
        [18],
        [ 5],
        [22]])]

In [47]:
# Divide into 4 equal arrays vertically(columnwise)
np.vsplit(arr, 4)

[array([[15, 17, 24, 28]]),
 array([[15, 20, 10, 18]]),
 array([[ 6, 18,  8,  5]]),
 array([[25, 17,  4, 22]])]

In [48]:
# Split after 2 and 4 column
np.hsplit(arr, (2, 4))

[array([[15, 17],
        [15, 20],
        [ 6, 18],
        [25, 17]]),
 array([[24, 28],
        [10, 18],
        [ 8,  5],
        [ 4, 22]]),
 array([], shape=(4, 0), dtype=int32)]

In [49]:
# Split after 1, 2 and 4 row
np.vsplit(arr, (1, 2, 4))

[array([[15, 17, 24, 28]]),
 array([[15, 20, 10, 18]]),
 array([[ 6, 18,  8,  5],
        [25, 17,  4, 22]]),
 array([], shape=(0, 4), dtype=int32)]

You can use the `view` method to create a new array object that looks at the same data as the original array (a shallow copy).

<p style="text-align:justify">Views are an important NumPy concept! NumPy functions, as well as operations like indexing and slicing, will return views whenever possible. This saves memory and is faster (no copy of the data has to be made). However it’s important to be aware of this - modifying data in a view also modifies the original array!</p>

In [50]:
arr

array([[15, 17, 24, 28],
       [15, 20, 10, 18],
       [ 6, 18,  8,  5],
       [25, 17,  4, 22]])

In [51]:
arr2 = arr[2:, 2:]
arr2[0, 0] = 2
arr

array([[15, 17, 24, 28],
       [15, 20, 10, 18],
       [ 6, 18,  2,  5],
       [25, 17,  4, 22]])

Using the `copy` method will make a complete copy of the array and its data (a deep copy).

In [52]:
arr2 = arr.copy()
arr2[0, 0] = 0
arr

array([[15, 17, 24, 28],
       [15, 20, 10, 18],
       [ 6, 18,  2,  5],
       [25, 17,  4, 22]])

### Basic array operations

In [53]:
arr1 = np.array([
                [14, 29,  8, 13],
                [23, 19, 20, 27],
                [29, 20,  2, 10],
                [26, 16,  7, 12]])
arr2 = np.array([
                [ 2, 20,  6, 11],
                [ 5,  9, 24, 27],
                [29, 11,  2,  7],
                [10,  8, 26, 17]])

Addition

In [54]:
arr1 + arr2

array([[16, 49, 14, 24],
       [28, 28, 44, 54],
       [58, 31,  4, 17],
       [36, 24, 33, 29]])

Subtraction

In [55]:
arr1 - arr2

array([[ 12,   9,   2,   2],
       [ 18,  10,  -4,   0],
       [  0,   9,   0,   3],
       [ 16,   8, -19,  -5]])

Multiplication

In [56]:
arr1 * arr2

array([[ 28, 580,  48, 143],
       [115, 171, 480, 729],
       [841, 220,   4,  70],
       [260, 128, 182, 204]])

Division

In [57]:
arr1 / arr2

array([[7.        , 1.45      , 1.33333333, 1.18181818],
       [4.6       , 2.11111111, 0.83333333, 1.        ],
       [1.        , 1.81818182, 1.        , 1.42857143],
       [2.6       , 2.        , 0.26923077, 0.70588235]])

you want to find the sum of the elements in an array, you’d use `sum()`. 

In [58]:
arr1.sum()

275

You can `sum` over the axis of rows with:

In [59]:
# Sum of columns
arr1.sum(axis=0)

array([92, 84, 37, 62])

You can `sum` over the axis of columns with:

In [60]:
# Sum of rows
arr1.sum(axis=1)

array([64, 89, 61, 61])

### Broadcasting

<p style="text-align:justify">There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes.</p>

In [61]:
arr1 * 2

array([[28, 58, 16, 26],
       [46, 38, 40, 54],
       [58, 40,  4, 20],
       [52, 32, 14, 24]])

In [62]:
arr1 + 5

array([[19, 34, 13, 18],
       [28, 24, 25, 32],
       [34, 25,  7, 15],
       [31, 21, 12, 17]])

### More useful array operations

In [63]:
arr1, arr2

(array([[14, 29,  8, 13],
        [23, 19, 20, 27],
        [29, 20,  2, 10],
        [26, 16,  7, 12]]),
 array([[ 2, 20,  6, 11],
        [ 5,  9, 24, 27],
        [29, 11,  2,  7],
        [10,  8, 26, 17]]))

In [64]:
# Minimum and Maxmum  Values
arr1.min(), arr2.max()

(2, 29)

In [65]:
# Minimum and Maxmum  from all columns
arr1.min(axis=0), arr2.max(axis=0)

(array([14, 16,  2, 10]), array([29, 20, 26, 27]))

In [66]:
# Minimum and Maxmum  from all rows
arr1.min(axis=1), arr2.max(axis=1)

(array([ 8, 19,  2,  7]), array([20, 27, 29, 26]))

In [67]:
# mean and standard deviation
arr1.mean(), arr2.std()

(17.1875, 8.852083088177608)

## Matrices

In [68]:
mat1 = np.array([
                [24, 14,  3, 14],
                [24, 16, 24, 18],
                [ 8,  4,  2,  7],
                [18, 16,  6, 23]])
mat2 = np.array([
                [ 7, 19, 14, 18],
                [13, 11, 17, 16],
                [12, 10,  7, 10],
                [13, 10, 12,  5]])

#### Transpose

In [69]:
mat1.T

array([[24, 24,  8, 18],
       [14, 16,  4, 16],
       [ 3, 24,  2,  6],
       [14, 18,  7, 23]])

In [70]:
mat2.transpose()

array([[ 7, 13, 12, 13],
       [19, 11, 10, 10],
       [14, 17,  7, 12],
       [18, 16, 10,  5]])

### Multiplication of Matrices

In [71]:
mat1.dot(mat2)

array([[ 568,  780,  763,  756],
       [ 898, 1052,  992, 1018],
       [ 223,  286,  278,  263],
       [ 705,  808,  842,  755]])

### Getting Unique Elements

In [72]:
arr1 = np.array([[9, 7, 1],
                [6, 4, 9],
                [4, 9, 1]])

In [73]:
np.unique(arr1)

array([1, 4, 6, 7, 9])

In [74]:
unique_values, indices_list = np.unique(arr1, return_index=True)
unique_values, indices_list

(array([1, 4, 6, 7, 9]), array([2, 4, 3, 1, 0], dtype=int64))

In [75]:
np.random.randint(1, 10, (3, 3))

array([[7, 6, 7],
       [3, 4, 4],
       [4, 8, 4]])

### How to reverse an array

In [76]:
arr

array([[15, 17, 24, 28],
       [15, 20, 10, 18],
       [ 6, 18,  2,  5],
       [25, 17,  4, 22]])

In [78]:
np.flip(arr)

array([[22,  4, 17, 25],
       [ 5,  2, 18,  6],
       [18, 10, 20, 15],
       [28, 24, 17, 15]])

In [80]:
np.flip(arr, axis=1)

array([[28, 24, 17, 15],
       [18, 10, 20, 15],
       [ 5,  2, 18,  6],
       [22,  4, 17, 25]])

### Flattening multidimensional arrays

There are two popular ways to flatten an array: `.flatten()` and `.ravel()`. The primary difference between the two is that the new array created using `ravel()` is actually a reference to the parent array (i.e., a “view”). This means that any changes to the new array will affect the parent array as well. Since ravel does not create a copy, it’s memory efficient.

In [81]:
arr

array([[15, 17, 24, 28],
       [15, 20, 10, 18],
       [ 6, 18,  2,  5],
       [25, 17,  4, 22]])

In [82]:
arr.flatten()

array([15, 17, 24, 28, 15, 20, 10, 18,  6, 18,  2,  5, 25, 17,  4, 22])

In [83]:
arr.ravel()

array([15, 17, 24, 28, 15, 20, 10, 18,  6, 18,  2,  5, 25, 17,  4, 22])

## How to access the docstring for more information

You can use `help()` to quickly find the information that you need.

In [85]:
help(np.max)

Help on function amax in module numpy:

amax(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Return the maximum of an array or maximum along an axis.
    
    Parameters
    ----------
    a : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        Axis or axes along which to operate.  By default, flattened input is
        used.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, the maximum is selected over multiple axes,
        instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternative output array in which to place the result.  Must
        be of the same shape and buffer length as the expected output.
        See :ref:`ufuncs-output-type` for more details.
    
    keepdims : bool, optional
        If this is set to True, the axes which are reduced are left
        in the result as dimensions with size one. With this option,
        the result

IPython uses the `?` character as a shorthand for accessing this documentation along with other relevant information. IPython is a command shell for interactive computing in multiple languages.

In [86]:
np.max?

Signature:
np.max(
    a,
    axis=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Docstring:
Return the maximum of an array or maximum along an axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which to operate.  By default, flattened input is
    used.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, the maximum is selected over multiple axes,
    instead of a single axis or all the axes as before.
out : ndarray, optional
    Alternative output array in which to place the result.  Must
    be of the same shape and buffer length as the expected output.
    See :ref:`ufuncs-output-type` for more details.

keepdims : bool, optional
    If this is set to True, the axes which are reduced are left
    in the result as dimensions with size one. With this option,
    the result will broadcast correctly against the input array.

    If the default value is p

You can reach another level of information by reading the source code of the object you’re interested in. Using a double question mark (`??`) allows you to access the source code.

If the object in question is compiled in a language other than Python, using `??` will return the same information as `?`. You’ll find this with a lot of built-in objects and types

In [87]:
np.max??

Signature:
np.max(
    a,
    axis=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Source:   
@array_function_dispatch(_amax_dispatcher)
def amax(a, axis=None, out=None, keepdims=np._NoValue, initial=np._NoValue,
         where=np._NoValue):
    """
    Return the maximum of an array or maximum along an axis.

    Parameters
    ----------
    a : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        Axis or axes along which to operate.  By default, flattened input is
        used.

        .. versionadded:: 1.7.0

        If this is a tuple of ints, the maximum is selected over multiple axes,
        instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternative output array in which to place the result.  Must
        be of the same shape and buffer length as the expected output.
        See :ref:`ufuncs-output-type` for more details.

    keepdims : bool, optional
    