## I'm Learning numpy

> **What is numpy?**
> <p style="text-align:justify">NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.</p>

#### Importing numpy

In [3]:
import numpy as np

#### Creating array

In [4]:
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

#### Diff. b/w python list and numpy array

In [5]:
import time

##### Python List Speed Test

In [8]:
python_list = [i for i in range(1000000)]
start_time = time.process_time()
add_two = [i+2 for i in python_list]
end_time = time.process_time()
end_time - start_time

0.078125

##### Numpy Array Speed Test

In [9]:
numpy_array = np.arange(1000000)
start_time = time.process_time()
add_two = numpy_array+2
end_time = time.process_time()
end_time - start_time

0.015625

In [86]:
# Deleting varaiables
del start_time, end_time, python_list, numpy_array, add_two

#### Arrays in numpy

1D Array

In [11]:
np.array([1, 2, 3, 4, 5], dtype=np.int8)

array([1, 2, 3, 4, 5], dtype=int8)

2D Array

In [12]:
np.array([[1, 2, 3, 4, 5],
          [6, 7, 8, 9, 10]], dtype=np.int8)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int8)

3D Array

In [15]:
np.array([[[1, 2, 3, 4, 5],
          [6, 7, 8, 9, 10]],
          
          [[1, 2, 3, 4, 5],
          [6, 7, 8, 9, 10]]], dtype=np.int8)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]], dtype=int8)

##### Arrays of Zeros

In [25]:
# 1D
print("1D:", np.zeros(2), "\n")
# 2D
print("2D:", np.zeros((2, 2)), "\n")
# 3D
print("3D:", np.zeros((2, 2, 2)), "\n")

1D: [0. 0.] 

2D: [[0. 0.]
 [0. 0.]] 

3D: [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]] 



##### Arrays of Ones

In [26]:
# 1D
print("1D:", np.ones(2), "\n")
# 2D
print("2D:", np.ones((2, 2)), "\n")
# 3D
print("3D:", np.ones((2, 2, 2)), "\n")

1D: [1. 1.] 

2D: [[1. 1.]
 [1. 1.]] 

3D: [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]] 



##### Empty Array
The function `np.empty()` creates an array whose initial content is random and depends on the state of the memory.

In [37]:
# 2x2 empty array
np.empty((2, 2))

array([[ 25.,  50.],
       [ 75., 100.]])

Creating an Array with a range of elements using `np.arange()` function similar to `range()` function

In [34]:
np.arange(100, 1, -2)

array([100,  98,  96,  94,  92,  90,  88,  86,  84,  82,  80,  78,  76,
        74,  72,  70,  68,  66,  64,  62,  60,  58,  56,  54,  52,  50,
        48,  46,  44,  42,  40,  38,  36,  34,  32,  30,  28,  26,  24,
        22,  20,  18,  16,  14,  12,  10,   8,   6,   4,   2])

You can also use `np.linspace()` to create an array with values that are spaced linearly in a specified interval

In [35]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

##### Random Arrays

In [39]:
np.random.rand(5, 5)

array([[0.52183287, 0.86206443, 0.51311366, 0.77330599, 0.45347846],
       [0.96764224, 0.95438479, 0.98086156, 0.40751283, 0.56217458],
       [0.82348372, 0.15327789, 0.9308583 , 0.79154737, 0.44778758],
       [0.80433836, 0.35069745, 0.95742454, 0.62307278, 0.78794666],
       [0.14098421, 0.71354184, 0.82281479, 0.02104877, 0.483753  ]])

In [51]:
np.random.randint(1, 10, (4, 4), dtype=np.int16)

array([[6, 5, 9, 2],
       [6, 7, 2, 4],
       [3, 3, 5, 1],
       [7, 8, 9, 3]], dtype=int16)

In [45]:
# Returns random float array of given size
np.random.random((3, 3))

array([[0.10066121, 0.47082982, 0.46926606],
       [0.89698418, 0.37521149, 0.32496044],
       [0.92499572, 0.29736966, 0.56318627]])

To sample from N evenly spaced floating-point numbers between a and b, use:

```a + (b - a) * (np.random.random_integers(N) - 1) / (N - 1.)```

In [49]:
np.random.random_integers(1, 5, size=(2, 2))

C:\Users\hp\AppData\Local\Temp\ipykernel_7220\1565548986.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  np.random.random_integers(1, 5, size=(2, 2))


array([[3, 5],
       [4, 2]])

##### Randomly Shuffling an Array

In [54]:
arr = np.arange(1, 10)
np.random.shuffle(arr)
arr

array([7, 2, 4, 5, 6, 3, 9, 1, 8])

##### Sorting
Sorting an element is simple with `np.sort()`. You can specify the axis, kind, and order when you call the function.

In [83]:
arr = np.array([[48, 60, 46,  1],
       [40, 63, 39, 55],
       [47, 37, 51, 53],
       [28, 25, 61, 99]])
arr

array([[48, 60, 46,  1],
       [40, 63, 39, 55],
       [47, 37, 51, 53],
       [28, 25, 61, 99]])

In [84]:
# Sorting along 1 axis
# Sorting ELements of each row
arr1 = arr.copy()
arr1.sort()
arr1

array([[ 1, 46, 48, 60],
       [39, 40, 55, 63],
       [37, 47, 51, 53],
       [25, 28, 61, 99]])

In [85]:
# Sorting along 0 axis
# Sorting Rows
arr2 = arr.copy()
arr2.sort(axis=0)
arr2

array([[28, 25, 39,  1],
       [40, 37, 46, 53],
       [47, 60, 51, 55],
       [48, 63, 61, 99]])

##### Concatenation

In [87]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

##### Checking shape, size, dimensions and datatype of numpy array

In [90]:
arr = np.random.randint(1, 10, (4, 4), dtype=np.int16)

arr.shape, arr.size, arr.ndim, arr.dtype

((4, 4), 16, 2, dtype('int16'))

##### Reshaping

In [91]:
arr.reshape((2, 8))

array([[4, 5, 9, 8, 2, 4, 4, 9],
       [9, 3, 4, 2, 5, 2, 7, 4]], dtype=int16)

#### How to convert a 1D array into a 2D array (how to add a new axis to an array)
You can use `np.newaxis` and `np.expand_dims` to increase the dimensions of your existing array.

In [102]:
arr = np.random.randint(1, 10, 16, dtype=np.int16)
arr.shape

(16,)

In [101]:
arr2 = arr[np.newaxis,:]
arr2.shape

(1, 16)

In [105]:
arr2 = arr[:, np.newaxis]
arr2.shape

(16, 1)

In [108]:
arr2 = np.expand_dims(arr, axis=0)
arr2

array([[1, 4, 8, 5, 8, 3, 4, 7, 7, 6, 7, 1, 8, 3, 4, 6]], dtype=int16)

In [109]:
arr2 = np.expand_dims(arr, axis=1)
arr2

array([[1],
       [4],
       [8],
       [5],
       [8],
       [3],
       [4],
       [7],
       [7],
       [6],
       [7],
       [1],
       [8],
       [3],
       [4],
       [6]], dtype=int16)

#### Indexing and Slicing

![Image](https://numpy.org/doc/stable/_images/np_indexing.png)

In [113]:
data = np.array([1, 2, 3])
data[-2:]

array([2, 3])